### PR TITLE
Make contributing easier with WYSIWYG editor

### PR DESCRIPTION
**Pull request by remorses**
After this PR is merged, users will be able to edit pages with the [Holocron](https://holocron.so) markdown editor.

[This](https://holocron.so/github/pr/nating/cs-exams/master/editor) is how the editor looks like for your repo.

Users can suggest edits to your docs without leaving the browser, and you can review and merge them with one click.

https://github.com/remorses/docusaurus-example/assets/31321188/43c8bc68-3668-4a25-bf1c-a70eceab7bcb

### CODE REVIEW

**Comment by nating** [comment]
Adding this would make it more difficult for students to make edits and would add unnecessary complexities to the workflow/project.

I'm not going to accept this merge request to add your business' product to this project. Best of luck with it though.

**Comment by remorses** [comment]
Why do you think it would make it more difficult?

**Comment by nating** [comment]
@remorses because the users have to authorize Holocron for their GitHub account. It also adds elements to the process of creating a pull request on GitHub that aren't usually there. A goal of this project is to introduce/familiarize students with the process of contributing to a project, and I think having another unusual element (Holocron - or whatever else) added in the middle of it is a jump in the wrong direction.

**Comment by remorses** [comment]
Thank you for the feedback! The goal of Holocron is to make contributing easier (after connecting Github the first time it's only 1 click), i understand it doesn't make sense for an educational project like in this case.

**Pull request closed without merging**
